version: '3.1'
services:
  sonarqube:
    image: sonarqube:7.9.1-community
    ports:
      - 9000:9000
#    depends_on:
#      - mysql-docker
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
#    environment:
#      SONARQUBE_JDBC_USERNAME: root
#      SONARQUBE_JDBC_PASSWORD: ${ROOT_PASSWORD}
#      SONARQUBE_JDBC_URL: jdbc:mysql://mysql-docker:3306/sonarqube?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    networks:
      - asgard

  mysql-docker:
   image: mysql:5.7.28
   environment:
     MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
   ports:
     - 3306:3306
   volumes:
   - ./opt/mysql:/var/lib/mysql
#   - ./initdata/initdb.sql:/docker-entrypoint-initdb.d/init.sql
   networks:
      - asgard

  phpmyadmin-docker:
    depends_on:
      - mysql-docker
    image: phpmyadmin:5-apache
    restart: always
    ports:
      - '80:80'
    environment:
      PMA_HOST: mysql-docker
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    networks:
      - asgard

networks:
  asgard:
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  jenkins-data:
