ALTER TABLE `T_SLOT` ADD `CONFIRM_CODE` VARCHAR(6) NULL AFTER `IDSTATUS`;

UPDATE `C_STATUS` SET `IDSTATUS` = '2006' WHERE `C_STATUS`.`IDSTATUS` = 2005;
UPDATE `C_STATUS` SET `IDSTATUS` = '2005' WHERE `C_STATUS`.`IDSTATUS` = 2004;
INSERT INTO `C_STATUS` (`IDSTATUS`, `STATUS`, `DESCRIPTION`, `OBJECT`) VALUES ('2004', 'CLOSED FOR SEND', 'The slot is closed and ready for send', 'T_SLOT');

CREATE TABLE IF NOT EXISTS `C_SHIPPINGMETHOD` (
  `IDSHIPPINGMETHOD` INT NOT NULL AUTO_INCREMENT,
  `KEY` VARCHAR(45) NULL,
  `NAME` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(45) NULL,
  `REQUIRE_ADDRESS` TINYINT NULL,
  `HAVE_TRACKING` TINYINT NULL,
  PRIMARY KEY (`IDSHIPPINGMETHOD`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `qslbureau_test`.`T_SHIP` (
  `IDSHIP` INT NOT NULL AUTO_INCREMENT,
  `DATETIME` DATETIME NOT NULL,
  `IDSLOT` INT NOT NULL,
  `IDSHIPPINGMETHOD` INT NOT NULL,
  `IDCAPTURER` INT NULL,
  `IDZONE` INT NULL,
  `ADDRESS` LONGTEXT NULL,
  `TRACKING_CODE` VARCHAR(70) NULL,
  `COMMENTS` VARCHAR(200) NULL,
  PRIMARY KEY (`IDSHIP`),
  INDEX `fk_T_SHIP_T_SLOT1_idx` (`IDSLOT` ASC),
  INDEX `fk_T_SHIP_C_SHIPPINGMETHOD1_idx` (`IDSHIPPINGMETHOD` ASC),
  INDEX `fk_T_SHIP_C_ZONE1_idx` (`IDZONE` ASC),
  INDEX `fk_T_SHIP_C_CAPTURER1_idx` (`IDCAPTURER` ASC),
  CONSTRAINT `fk_T_SHIP_T_SLOT1`
    FOREIGN KEY (`IDSLOT`)
    REFERENCES `T_SLOT` (`IDSLOT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_SHIP_C_SHIPPINGMETHOD1`
    FOREIGN KEY (`IDSHIPPINGMETHOD`)
    REFERENCES `C_SHIPPINGMETHOD` (`IDSHIPPINGMETHOD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_SHIP_C_ZONE1`
    FOREIGN KEY (`IDZONE`)
    REFERENCES `C_ZONE` (`IDZONE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_SHIP_C_CAPTURER1`
    FOREIGN KEY (`IDCAPTURER`)
    REFERENCES `C_CAPTURER` (`IDCAPTURER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `C_SHIPPINGMETHOD` (`IDSHIPPINGMETHOD`, `KEY`, `NAME`, `DESCRIPTION`, `REQUIRE_ADDRESS`, `HAVE_TRACKING`) VALUES ('1', 'PERSONAL', 'Personal', 'Entrega personal', '0', '0');
INSERT INTO `C_SHIPPINGMETHOD` (`IDSHIPPINGMETHOD`, `KEY`, `NAME`, `DESCRIPTION`, `REQUIRE_ADDRESS`, `HAVE_TRACKING`) VALUES ('2', 'REGIONAL', 'Entrega con partner regional', 'Entrega con partner regional', '0', '0');
INSERT INTO `C_SHIPPINGMETHOD` (`IDSHIPPINGMETHOD`, `KEY`, `NAME`, `DESCRIPTION`, `REQUIRE_ADDRESS`, `HAVE_TRACKING`) VALUES ('3', 'SEPOMEX', 'Servicio Postal Mexicano', 'Correpos - Servicio Postal Mexicano', '1', '0');
INSERT INTO `C_SHIPPINGMETHOD` (`IDSHIPPINGMETHOD`, `KEY`, `NAME`, `DESCRIPTION`, `REQUIRE_ADDRESS`, `HAVE_TRACKING`) VALUES ('4', 'MEXPOST', 'MEXPOST', 'Correpos - MEXPOST', '1', '1');

INSERT INTO `C_ZONE` (`IDZONE`, `NAME`, `START`, `END`) VALUES ('2', 'Puebla', NOW(), NULL);
INSERT INTO `C_ZONERULE` (`IDZONERULE`, `IDCAPTURER`, `IDZONE`, `CALLSIGN`, `START`, `END`) VALUES (NULL, '3', '2', 'XE1YL', NOW(), NULL);

INSERT INTO `C_STATUS` (`IDSTATUS`, `STATUS`, `DESCRIPTION`, `OBJECT`) VALUES ('2007', 'INTERNATIONAL', 'Moved to international', 'T_SLOT');

ALTER TABLE `T_SLOT` ADD `SENT_AT` DATETIME NULL DEFAULT NULL AFTER `CLOSED_AT`, ADD `MOVED_TO_INT_AT` DATETIME NULL DEFAULT NULL AFTER `SENT_AT`;


