CREATE TABLE IF NOT EXISTS `C_ZONE` (
  `IDZONE` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `START` DATETIME NULL,
  `END` DATETIME NULL,
  PRIMARY KEY (`IDZONE`))
ENGINE = InnoDB;

ALTER TABLE `C_ZONERULE` ADD `END` DATETIME NULL DEFAULT NULL AFTER `START`;

ALTER TABLE `C_ZONERULE` DROP `ZONE`;

ALTER TABLE `C_ZONERULE` ADD `IDZONE` INT NULL DEFAULT NULL AFTER `IDCAPTURER`;

ALTER TABLE `C_ZONERULE` ADD CONSTRAINT `fk_C_ZONERULE_C_ZONE1` FOREIGN KEY (IDZONE) REFERENCES C_ZONE(IDZONE);

ALTER TABLE `C_ZONERULE` CHANGE `IDZONE` `IDZONE` INT(11) NOT NULL;

INSERT INTO `C_ZONE` (`IDZONE`, `NAME`, `START`, `END`) VALUES (1, 'Todo Queretaro', NOW(), NULL);

INSERT INTO `C_CAPTURER` (`IDCAPTURER`, `NAME`, `LASTNAME`, `USERNAME`, `PASSWORD`, `START`, `END`) VALUES (2, 'Alejandro', 'Valdez', 'xe1ee', 'xxxxxx', NOW(), NULL);
INSERT INTO `C_CAPTURER` (`IDCAPTURER`, `NAME`, `LASTNAME`, `USERNAME`, `PASSWORD`, `START`, `END`) VALUES (3, 'Ricardo', 'Orozco', 'xe1sov', 'xxxxxx', NOW(), NULL);


INSERT INTO `C_ZONERULE` (`IDZONERULE`, `IDCAPTURER`, `IDZONE`, `CALLSIGN`, `START`, `END`) VALUES (NULL, '2', '1', 'XE1RUZ', NOW(), NULL);
INSERT INTO `C_ZONERULE` (`IDZONERULE`, `IDCAPTURER`, `IDZONE`, `CALLSIGN`, `START`, `END`) VALUES (NULL, '2', '1', 'XE1CL', NOW(), NULL);
INSERT INTO `C_ZONERULE` (`IDZONERULE`, `IDCAPTURER`, `IDZONE`, `CALLSIGN`, `START`, `END`) VALUES (NULL, '2', '1', 'XE1GSY', NOW(), NULL);
INSERT INTO `C_ZONERULE` (`IDZONERULE`, `IDCAPTURER`, `IDZONE`, `CALLSIGN`, `START`, `END`) VALUES (NULL, '2', '1', 'XE1YZY', NOW(), NULL);
INSERT INTO `C_ZONERULE` (`IDZONERULE`, `IDCAPTURER`, `IDZONE`, `CALLSIGN`, `START`, `END`) VALUES (NULL, '2', '1', 'XE1YO', NOW(), NULL);
INSERT INTO `C_ZONERULE` (`IDZONERULE`, `IDCAPTURER`, `IDZONE`, `CALLSIGN`, `START`, `END`) VALUES (NULL, '2', '1', 'XE1EE', NOW(), NULL);